[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 5173
  autoLaunch = false

[[redirects]]
  from = "https://www.altroofingsolutions.com/*"
  to = "https://altroofingsolutions.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://altroofingsolutions.com/*"
  to = "https://altroofingsolutions.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.altroofingsolutions.com/*"
  to = "https://altroofingsolutions.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
